<a href="https://colab.research.google.com/github/Akshay2903/Numpy-and-Linear-Algebra/blob/master/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Matrices**

In [6]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
print (A)

[[1 2 3]
 [4 5 6]]


## Matrix transposition

In [1]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


## Matrix Multiplication

In [9]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[9,8],
              [7,6],
              [5,4]])
print(np.dot(A,B))
print(A @ B)

[[ 38  32]
 [101  86]]
[[ 38  32]
 [101  86]]


In [10]:
import numpy as np

A = np.matrix([[1,2,3]
               ,[4,5,6]])
B = np.matrix([[9,8],
               [7,6],
               [5,4]])
print(A * B)

[[ 38  32]
 [101  86]]


In [11]:
#check whether the commutative law is applicable to the matrix multiplications

import numpy as np

A = np.array([[2,4],
              [6,8]])
B = np.array([[1,3],
              [5,7]])
print(A @ B)
print(B @ A)

[[22 34]
 [46 74]]
[[20 28]
 [52 76]]


## Inverse of Matrix

In [12]:
import numpy as np

B = np.array([[6,2],
              [1,2]])

print(np.linalg.inv(B))

[[ 0.2 -0.2]
 [-0.1  0.6]]


In [14]:
import numpy as np
B = np.matrix([[6,2],
              [1,2]])
print(B.I)

[[ 0.2 -0.2]
 [-0.1  0.6]]


In [15]:
import numpy as np

B = np.array([[6,2,1],
              [1,2,1],
              [2,3,4]])

print(np.linalg.inv(B))

[[ 2.00000000e-01 -2.00000000e-01  9.25185854e-18]
 [-8.00000000e-02  8.80000000e-01 -2.00000000e-01]
 [-4.00000000e-02 -5.60000000e-01  4.00000000e-01]]
