<a href="https://colab.research.google.com/github/Akshay2903/Numpy-and-Linear-Algebra/blob/master/Rank_of_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Rank of matrix

In [1]:
#lets find the eigenvalue of matrix A
import numpy as np
A = np.array([[1,2],
              [4,3]])
l, Q = np.linalg.eig(A)
L = np.diag(l)
print(L)

[[-1.  0.]
 [ 0.  5.]]


In [2]:
#lets examine another matrix of 3*3
B = np.array([[3,-3,6],
              [2,-2,4],
              [1,-1,2]])
lb, Qb = np.linalg.eig(B)
Lb = np.diag(lb)
print(Lb)

[[3.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.23364153e-16 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]


## Inverse of a Square Full Rank Matrix

In [3]:
import numpy as np
A = np.array([[1,2],
              [4,3]])

l, Q = np.linalg.eig(A)
L = np.diag(l)
print(Q)
Linv = np.linalg.inv(L)
Qinv = np.linalg.inv(Q)
print(Linv)
print(Qinv)

[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]
[[-1.  -0. ]
 [ 0.   0.2]]
[[-0.94280904  0.47140452]
 [-0.74535599 -0.74535599]]


In [4]:
Ainv = (Q@(Linv@(Qinv)))
print(Ainv)

[[-0.6  0.4]
 [ 0.8 -0.2]]


In [5]:
print(np.linalg.inv(A))

[[-0.6  0.4]
 [ 0.8 -0.2]]
